name: Feature Branch Workflow

on:
  pull_request:
    branches: [ feature ]

jobs:
  # This step will build the maven application
  build_app:
    name: Build Application with Maven
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    #- uses: actions/setup-java@v1
    #  with: 
    #    java-version: 1.8
    #- name: Cache Maven packages
    #  uses: actions/cache@v2
    #  with:
    #    path: ~/.m2
    #    key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
    - name: Build with Maven
    #  run: mvn clean package
      run: echo "Builing package"

    - uses: actions/upload-artifact@v1
      with:
        name: verademo.war
        path: target/verademo.war


  software-composition-analysis:
    name: Software Composition Analysis
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with: 
        java-version: 1.8
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
    - run: curl -sSL https://download.sourceclear.com/ci.sh | bash -s scan . --update-advisor 2>&1 | tee sca_output.txt
      env:
        SRCCLR_API_TOKEN: ${{secrets.SRCCLR_API_TOKEN}}
    - uses: actions/upload-artifact@v1
      with:
        name: SCAScanResults
        path: sca_output.txt

  pipeline_scan:
      # needs the build step before this job will start running
      name: Pipeline Scan
      needs: build_app
      runs-on: ubuntu-latest

      steps:
        - name: checkout repo
          uses: actions/checkout@v2
        
        # get the compiled binary from a previous job
        - name: get archive
          uses: actions/download-artifact@v2
          with:
            name: verademo.war

        # run the pipeline scan action
        - name: pipeline-scan action step
          id: pipeline-scan
          uses: veracode/Veracode-pipeline-scan-action@pipeline-scan-beta-v0.0.3
          with:
            vid: ${{secrets.VID}}
            vkey: ${{secrets.VKEY}}
            file: "verademo.war"
            baseline_file: "verademo_results.json"
      
        - name: Store filtered results
          uses: actions/upload-artifact@v1
          with:
            name: filtered_results
            path: filtered_results.json

  import-findings-to-code-scanning-alerts:
    name: Import Flaws To GitHub Code Scanning
    needs: pipeline_scan
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: get scan results
        uses: actions/download-artifact@v2
        with:
          name: "Veracode Pipeline-Scan Results"
      
      - name: Convert pipeline scan output to SARIF format 
        id: convert
        uses: veracode/veracode-pipeline-scan-results-to-sarif@v0.1.5
        with:
          pipeline-results-json: results.json
          source-base-path-1: "^com/veracode:src/main/java/com/veracode"
          source-base-path-2: "^WEB-INF:src/main/webapp/WEB-INF"
      
      - name: Upload SARIF File
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: veracode-results.sarif

  import-policy-flaws:
    name: Import Flaws To GitHub Issues
    needs: pipeline_scan
    runs-on: ubuntu-latest
    steps:
      - name: get flaw file
        uses: actions/download-artifact@v2
        with:
          name: Veracode Pipeline-Scan Results
          path: /tmp

      - name: import flaws as issues
        uses: julz0815/veracode-flaws-to-issues@beta-0.0.105
        with:
          scan-results-json: '/tmp/filtered_results.json'
          source-base-path_1: "com/veracode:src/main/java/com/veracode"
          source-base-path_2: "WEB-INF:src/main/webapp/WEB-INF"
